name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["type:feature", "priority:p2"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the sections below.
        
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is your feature request related to a problem?
      placeholder: I'm always frustrated when...
    validations:
      required: true
      
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: I would like to see...
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: I also considered...
    validations:
      required: false
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would help productivity
        - High - Blocking current work
        - Critical - Cannot continue without this
    validations:
      required: true
      
  - type: dropdown
    id: client
    attributes:
      label: Client/Project
      description: Which client or project is this for?
      options:
        - Client A
        - Client B  
        - Client C
        - Internal
        - Multiple clients
    validations:
      required: false
      
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
    validations:
      required: false
